### ISSUE TITLE
Should we automatically set a readable max-width on select elements?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#153]
Initial conversation is here: https://github.com/cfpb/cfgov-refresh/pull/147#discussion_r17803144

Some questions that come to mind are:

### 1. What elements would need to be targeted?

```less
h1-6, p, ul
```

### 2. What approach should we take?

Target the elements directly?
```less
h1-6, p, ul { max-width: @readable-max-width; }
```

Target the elements when inside of a class?
```less
.readable-max { h1-6, p, ul { max-width: @readable-max-width; } }
```

Add a class to anything you want to have a max-width? (this is not automatic but worth mentioning)
```less
.readable-max { max-width: @readable-max-width; }
```
