### ISSUE TITLE
Print styles

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfgov-refresh#248]
I'm likely developing print styles for [Owning a Home](https://github.com/cfpb/owning-a-home) and would like to contribute some back to the refresh. @himedlooff has started work at https://github.com/cfpb/cfgov-refresh/tree/gh-pages/docs/print

Some print style standards to start:

* [x] output link href attribute
* [ ] output URLs for media like youtube videos, share? or hide them?
* [x] use [HTML5 boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L205) as template

**Comment by himedlooff** [comment]
:+1: 

The approach we're taking in cfgov-refresh is to have print styles in both `@media print` and nested under a `.print` class. This allows us to have certain pages that have the print-look in the browser by adding the `print` class to the `body`. We're doing this with a mixin called [ `respond-to-print`](https://github.com/cfpb/cfgov-refresh/blob/c4a3512be7bf659cfe4127f1cb6e936df91dbe49/static/css/cf-enhancements.less#L75).

Example usage:

```less
.superheader {
    .respond-to-print({
        color: @green;
    });
}
```

compiles to:

```css
@media print {
  .superheader {
    color: #2cb34a;
  }
}
.print .superheader {
  color: #2cb34a;
}
```
